name: Check Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Node.js cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run build

      - name: Check links with markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.markdownlinkcheck.json'

      - name: Check HTML files for basic issues
        run: |
          # Basic HTML file validation without external dependencies
          echo "Checking built HTML files..."

          # Check if essential files exist
          find .vitepress/dist -name "*.html" -type f | head -10

          # Check for broken internal links (basic)
          for file in .vitepress/dist/*.html; do
            if [ -f "$file" ]; then
              echo "✓ Found: $(basename "$file")"
            fi
          done

          echo "✅ HTML files structure looks good"